version: "3.8"

services:
  firewall-agent:
    build:
      context: ..
      dockerfile: firewall-agent/Dockerfile
    image: firewall-agent:local
    network_mode: host
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - FIREWALL_ALLOWED_SERVICES=traefik,jellyfin,gluetun
      - FIREWALL_RESTRICT_LABEL=firewall.restrict
      - FIREWALL_API_HOST=0.0.0.0
      - FIREWALL_API_PORT=9443
      - FIREWALL_LOG_LEVEL=INFO
    # The agent is idempotent and can re-apply at any time.
    # In Swarm, strict service start ordering is not guaranteed.
