name: Build and Push UI

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
    paths:
      - 'firewall-agent-ui/**'
      - '.github/workflows/build-ui.yml'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'firewall-agent-ui/**'
      - '.github/workflows/build-ui.yml'
  workflow_dispatch: {}

concurrency:
  group: build-ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push firewall-agent-ui
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/firewall-agent-ui
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: firewall-agent-ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
